import { Product } from '../types';

export const initialProducts: Product[] = [
  {
    productId: 'VEG001',
    category: 'Vegetables',
    productName: 'Onion',
    imageUrl: `https://source.unsplash.com/400x300/?fresh-onions`,
    unit: 'kg',
    pricePerUnit: 40,
    minOrderQty: 50,
    stockStatus: 'In Stock',
    lastUpdated: '2024-05-20',
    description: 'Fresh, pungent red onions, sourced from the best farms in Nashik. Perfect for a wide range of culinary applications.',
    tags: ['Nashik Origin', 'A-Grade', 'Staple'],
  },
  {
    productId: 'VEG002',
    category: 'Vegetables',
    productName: 'Tomato',
    imageUrl: `https://source.unsplash.com/400x300/?ripe-tomatoes`,
    unit: 'kg',
    pricePerUnit: 30,
    minOrderQty: 50,
    stockStatus: 'In Stock',
    lastUpdated: '2024-05-20',
    description: 'Juicy, ripe tomatoes with a vibrant red color. Ideal for salads, sauces, and curries.',
    tags: ['Hybrid', 'A-Grade'],
  },
  {
    productId: 'VEG003',
    category: 'Vegetables',
    productName: 'Garlic',
    imageUrl: `https://source.unsplash.com/400x300/?garlic-bulbs`,
    unit: 'kg',
    pricePerUnit: 120,
    minOrderQty: 20,
    stockStatus: 'Low Stock',
    lastUpdated: '2024-05-20',
    description: 'Aromatic and flavorful garlic bulbs. An essential ingredient for adding depth to any dish.',
    tags: ['Organic', 'Pungent'],
  },
  {
    productId: 'FRU001',
    category: 'Fruits',
    productName: 'Apple',
    imageUrl: `https://source.unsplash.com/400x300/?red-apples`,
    unit: 'kg',
    pricePerUnit: 150,
    minOrderQty: 25,
    stockStatus: 'In Stock',
    lastUpdated: '2024-05-20',
    description: 'Crisp and sweet Royal Gala apples, sourced from Himachal Pradesh. Perfect for fresh consumption or baking.',
    tags: ['Royal Gala', 'Premium'],
  },
  {
    productId: 'FRU002',
    category: 'Fruits',
    productName: 'Mango',
    imageUrl: `https://source.unsplash.com/400x300/?ripe-mangoes`,
    unit: 'dozen',
    pricePerUnit: 800,
    minOrderQty: 10,
    stockStatus: 'In Stock',
    lastUpdated: '2024-05-20',
    description: 'Sweet and fragrant Alphonso mangoes, the king of fruits. Sourced from the Konkan region.',
    tags: ['Alphonso', 'Seasonal', 'Export Quality'],
  },
  {
    productId: 'EXO001',
    category: 'Exotic',
    productName: 'Avocado',
    imageUrl: `https://source.unsplash.com/400x300/?fresh-avocado`,
    unit: 'piece',
    pricePerUnit: 180,
    minOrderQty: 30,
    stockStatus: 'Out of Stock',
    lastUpdated: '2024-05-19',
    description: 'Creamy and nutritious Hass avocados, imported for superior quality.',
    tags: ['Imported', 'Hass'],
  },
];